name: run python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}
      ALPHA_VANTAGE_URL: ${{ secrets.ALPHA_VANTAGE_URL }}
      ALPHA_API_KEY: ${{ secrets.ALPHA_API_KEY }}
      GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      REVENUE_PERCENTAGE: ${{ vars.REVENUE_PERCENTAGE }}      
      SYMBOLS_INTEREST_LIST: ${{ vars.SYMBOLS_INTEREST_LIST }}      
      MAILING_LIST: ${{ vars.MAILING_LIST }}      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Usa la versión de Python que prefieras

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: |
          pytest -v
