name: run process

on:
  schedule:
    - cron: '0 5 * * *'  # Ejecutar a las 07:00 UTC diariamente
  workflow_dispatch:

permissions:
  contents: write  # Permitir push en main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rama main
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias (si hay requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar main.py
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
          GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}
          GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
        run: python main.py
