name: run process

on:
  schedule:
    - cron: '0 5 * * *'  # Ejecutar a las 07:00 UTC diariamente
  workflow_dispatch:

permissions:
  contents: write  # Permitir push en main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rama main
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias (si hay requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar main.py
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
        run: python main.py

      - name: Commit y push cambios en main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "manu-gt-hub"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.csv
          git commit -m "Actualizar CSV automáticamente [ci skip]" || echo "No hay cambios"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push --force origin main
