name: run process

on:
  schedule:
    - cron: '0 6 * * *'  # Ejecutar a las 06:00 UTC diariamente
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias (si hay requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar main.py
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
        run: python main.py
        
      - name: Commit y push de cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.csv
          git commit -m "Actualizar CSV automáticamente [ci skip]" || echo "No hay cambios"
          git push -u origin data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
